name: "Install Certinfo"
description: "Copy Certinfo binary and add it to the PATH"
branding:
  icon: shield
  color: blue
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/setup.sh
      shell: bash